#! Local use only
version: "3.8"

services:

  flask:
    build: ./miagenda
    container_name: flask
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./miagenda:/app
    environment:
      - PORT=8080
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@pgsql:5432/miagenda

  pgsql:
    image: postgres:13-alpine
    container_name: pgsql
    env_file:
      - database.env
    volumes:
      - .database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
