"""empty message

Revision ID: fa199c10d59f
Revises: 
Create Date: 2021-10-26 05:06:53.854495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa199c10d59f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materias',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('profesor', sa.String(), nullable=True),
    sa.Column('enlaces', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agenda_materia',
    sa.Column('agenda_id', sa.BigInteger(), nullable=False),
    sa.Column('materia_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('agenda_id', 'materia_id')
    )
    op.create_table('cuentas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contraseña', sa.String(), nullable=True),
    sa.Column('correo', sa.String(), nullable=True),
    sa.Column('escuela', sa.String(), nullable=True),
    sa.Column('agenda_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horarios',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('inicio', sa.Float(), nullable=True),
    sa.Column('final', sa.Float(), nullable=True),
    sa.Column('duracion', sa.Float(), nullable=True),
    sa.Column('dias', sa.String(), nullable=True),
    sa.Column('materia_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sesiones',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dispositivo', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('cuenta_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sesiones')
    op.drop_table('horarios')
    op.drop_table('cuentas')
    op.drop_table('agenda_materia')
    op.drop_table('materias')
    op.drop_table('agendas')
    # ### end Alembic commands ###
